[package]
name = "web-scoket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
juri = { path = "../../juri" }
async-std = { version = "1.12.0", features = ["attributes"] }